name: Deploy to DeploysCustom.app
description: Deploy docker image to deploysCustom.app
author: DeploysCustom.app
branding:
  color: red
  icon: cloud
inputs:
  project:
    description: Project ID
    required: true
  location:
    description: Deploy Location ID
    required: true
  name:
    description: Deployment Name or Master Project Name
    required: true
  image:
    description: Docker Image to deploy
    required: true
  type:
    description: Deployment Type
    required: true
  form:
    description: Copy And Deployment to Name
    required: false

runs:
  using: node16
  main: dist/index.js
