name: Deploy to DeploysCustom.app
description: Deploy docker image to deploysCustom.app
author: DeploysCustom.app
branding:
  color: yellow
  icon: cloud
inputs:
  project:
    description: Project ID
    required: true
  location:
    description: Deploy Location ID
    required: true
  name:
    description: Deployment Name or Master Project Name
    required: true
  image:
    description: Docker Image to deploy
    required: false
  type:
    description: Deployment Type
    required: true
  from:
    description: Copy And Deployment to Name
    required: false
  minReplicas:
    description: Minimum Replicas
    required: false
    default: "1"
  maxReplicas:
    description: Maximum Replicas
    required: false
    default: "1"
  portDeployApp:
    description: Port Deploy App
    required: false
    default: "8080"
  tokenTelegram:
    description: Telegram Token
    required: false
    default: ""
  chatIdTelegram:
    description: Telegram Token
    required: false
    default: ""
  clickUpToken:
    description: ClickUp Token
    required: false
    default: ""
  clickUpTeamId:
    description: ClickUp Team ID
    required: false
    default: ""

runs:
  using: node16
  main: dist/index.js
